name: Generate Christmas lottery and PR

on:
  push
# schedule:
# - cron: "0 0 10 11 *"

jobs:
  build-christmas:
    runs-on: ubuntu-latest
    env:
      ANNIKA_SECRET_KEY: ${{ vars.ANNIKA_SECRET_KEY }}
      ELIN_SECRET_KEY: ${{ vars.ELIN_SECRET_KEY }}
      GUSTAF_SECRET_KEY: ${{ vars.GUSTAF_SECRET_KEY }}
      JOHAN_SECRET_KEY: ${{ vars.JOHAN_SECRET_KEY }}
      MAGNUS_SECRET_KEY: ${{ vars.MAGNUS_SECRET_KEY }}
      OLIVIA_SECRET_KEY: ${{ vars.OLIVIA_SECRET_KEY }}
      PER_SECRET_KEY: ${{ vars.PER_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run generation script
        working-directory: ./christmas
        run: |
          deno run -A script/santa.ts lottery --inputJson data/lottery.json

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "(bot) generate christmas lottery"
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-christmas-lottery
          title: "Update Christmas Lottery"
          body: ":christmas_tree::gift:"
