name: Build Christmas and PR

on:
  push
    #tags:
    #- 'v*'

jobs:
  build-christmas:
    runs-on: ubuntu-latest
    env:
      ANNIKA_SECRET_KEY: ${{ vars.ANNIKA_SECRET_KEY }}
      ELIN_SECRET_KEY: ${{ vars.ELIN_SECRET_KEY }}
      GUSTAF_SECRET_KEY: ${{ vars.GUSTAF_SECRET_KEY }}
      JOHAN_SECRET_KEY: ${{ vars.JOHAN_SECRET_KEY }}
      MAGNUS_SECRET_KEY: ${{ vars.MAGNUS_SECRET_KEY }}
      OLIVIA_SECRET_KEY: ${{ vars.OLIVIA_SECRET_KEY }}
      PER_SECRET_KEY: ${{ vars.PER_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Debug Environment Variables
        run: env

      - name: Run build script
        run: |
          cd christmas
          echo "HELOO!"
          echo $ANNIKA_SECRET_KEY
          deno run -A script/build.ts --buildDir dist
          mv dist/index.html ../dist/christmas
          cd ..

      # - name: Create a new branch for changes
        # run: |
          # git config --global user.name "github-actions"
          # git config --global user.email "github-actions@github.com"

          # TIME_IDENTIFIER=$(date +"%Y-%m-%d-%H-%M")

          # git checkout -b update-html-${TIME_IDENTIFIER}

          # git add .
          # git commit -m "${TIME_IDENTIFIER}: Update generated HTML files"
          # git push --set-upstream origin update-html-${TIME_IDENTIFIER}

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "${TIME_IDENTIFIER}: Regenerate Christmas Lottery"
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-html-${TIME_IDENTIFIER}
          title: "Update lottery for ${TIME_IDENTIFIER}"
          body: "This pull request includes updates to the generated HTML files (${TIME_IDENTIFIER})."
