name: Build Christmas and PR

on:
  push
    #tags:
    #- 'v*'

jobs:
  build-christmas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Debug Environment Variables
        run: env

      - name: Run build script
        run: |
          cd christmas
          echo "HELOO!"
          echo $ANNIKA_SECRET_KEY
          deno run -A script/build.ts --buildDir dist
          mv dist/index.html ../dist/christmas
          cd ..

      # - name: Create a new branch for changes
      #   run: |
      #     git config --global user.name "github-actions"
      #     git config --global user.email "github-actions@github.com"

      #     YEAR=$(date +'%Y')

      #     git checkout -b update-html-${YEAR}

      #     git add .
      #     git commit -m "Update generated HTML files for year ${YEAR}"
      #     git push --set-upstream origin update-html-${YEAR}

      # - name: Create a pull request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     base: main
      #     head: update-html-${YEAR}
      #     title: "Update lottery for ${YEAR}"
      #     body: "This pull request includes updates to the generated HTML files for the year ${YEAR}."
