name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Lint
        working-directory: ./christmas
        run: |
          deno lint
          deno fmt --check

      - name: Build Christmas
        working-directory: ./christmas
        run: deno run -A script/santa.ts build --buildDir ../dist/christmas --json data/lottery.json

      - name: Move static files and CNAME
        run: |
          cp -r static/* dist
          cp CNAME dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
